// src/lib/niche-intelligence-seed.ts
// Run: npx tsx src/lib/niche-intelligence-seed.ts
import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'
import * as dotenv from 'dotenv'
dotenv.config()

const pool = new Pool({ connectionString: process.env.DATABASE_URL! })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

export const NICHE_INTELLIGENCE_DATA = [
  {
    slug: 'artificial_intelligence',
    displayName: 'Artificial Intelligence',
    avgCompetitionScore: 45,
    avgDomainAge: 4.2,
    avgDR: 38,
    topResultsHaveExpired: true,
    totalKeywords: 48000,
    avgMonthlySearches: 12400,
    topKeywordVolume: 246000,
    topKeyword: 'best ai tools',
    avgCPC: 4.20,
    affiliateAvailable: true,
    avgCommission: 30,
    estimatedRPM: 18,
    monthlyRevenuePerSite: 340,
    parasiteSuccessRate: 68,
    avgTimeToRank: 7,
    expiredDomainsAvailable: 847,
    indexationRate: 82,
    competitorCount: 340,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best ai tools', volume: 246000, cpc: 4.50, difficulty: 62 },
      { keyword: 'ai writing tools', volume: 135000, cpc: 5.20, difficulty: 58 },
      { keyword: 'free ai tools', volume: 90500, cpc: 2.10, difficulty: 55 },
      { keyword: 'ai image generator', volume: 823000, cpc: 1.80, difficulty: 71 },
      { keyword: 'chatgpt alternatives', volume: 74000, cpc: 6.30, difficulty: 49 },
    ],
    affiliatePrograms: [
      { name: 'Jasper AI', commission: '30% recurring', cookie: '30 days', network: 'Direct' },
      { name: 'Copy.ai', commission: '$23/sale', cookie: '60 days', network: 'Direct' },
      { name: 'Writesonic', commission: '30% recurring', cookie: '30 days', network: 'Direct' },
    ],
  },
  {
    slug: 'finance',
    displayName: 'Finance & Investing',
    avgCompetitionScore: 72,
    avgDomainAge: 7.8,
    avgDR: 58,
    topResultsHaveExpired: false,
    totalKeywords: 320000,
    avgMonthlySearches: 28000,
    topKeywordVolume: 1200000,
    topKeyword: 'best credit cards',
    avgCPC: 18.40,
    affiliateAvailable: true,
    avgCommission: 45,
    estimatedRPM: 42,
    monthlyRevenuePerSite: 890,
    parasiteSuccessRate: 31,
    avgTimeToRank: 21,
    expiredDomainsAvailable: 234,
    indexationRate: 61,
    competitorCount: 1200,
    difficulty: 'HARD',
    opportunity: 'GOOD',
    topKeywords: [
      { keyword: 'best credit cards 2026', volume: 673000, cpc: 22.50, difficulty: 88 },
      { keyword: 'how to invest money', volume: 450000, cpc: 12.30, difficulty: 75 },
      { keyword: 'best savings account', volume: 368000, cpc: 19.80, difficulty: 82 },
      { keyword: 'crypto trading platforms', volume: 201000, cpc: 8.90, difficulty: 71 },
      { keyword: 'personal finance tips', volume: 135000, cpc: 6.40, difficulty: 63 },
    ],
    affiliatePrograms: [
      { name: 'Coinbase', commission: '$10/signup', cookie: '30 days', network: 'Direct' },
      { name: 'Robinhood', commission: '$5-20/lead', cookie: '30 days', network: 'Impact' },
      { name: 'Credit Cards (CJ)', commission: '$50-200/approval', cookie: '45 days', network: 'CJ' },
    ],
  },
  {
    slug: 'health_wellness',
    displayName: 'Health & Wellness',
    avgCompetitionScore: 58,
    avgDomainAge: 5.1,
    avgDR: 44,
    topResultsHaveExpired: true,
    totalKeywords: 890000,
    avgMonthlySearches: 18600,
    topKeywordVolume: 550000,
    topKeyword: 'weight loss tips',
    avgCPC: 3.80,
    affiliateAvailable: true,
    avgCommission: 35,
    estimatedRPM: 22,
    monthlyRevenuePerSite: 420,
    parasiteSuccessRate: 54,
    avgTimeToRank: 12,
    expiredDomainsAvailable: 1240,
    indexationRate: 74,
    competitorCount: 680,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'weight loss tips', volume: 550000, cpc: 2.40, difficulty: 67 },
      { keyword: 'best supplements', volume: 301000, cpc: 5.60, difficulty: 61 },
      { keyword: 'keto diet plan', volume: 246000, cpc: 3.20, difficulty: 58 },
      { keyword: 'intermittent fasting', volume: 823000, cpc: 2.80, difficulty: 64 },
      { keyword: 'best protein powder', volume: 450000, cpc: 4.10, difficulty: 59 },
    ],
    affiliatePrograms: [
      { name: 'iHerb', commission: '5-10%', cookie: '7 days', network: 'Direct' },
      { name: 'ClickBank Health', commission: '50-75%', cookie: '60 days', network: 'ClickBank' },
      { name: 'Amazon Associates', commission: '3-8%', cookie: '24 hours', network: 'Amazon' },
    ],
  },
  {
    slug: 'digital_marketing',
    displayName: 'Digital Marketing',
    avgCompetitionScore: 52,
    avgDomainAge: 4.8,
    avgDR: 41,
    topResultsHaveExpired: true,
    totalKeywords: 125000,
    avgMonthlySearches: 8900,
    topKeywordVolume: 368000,
    topKeyword: 'seo tools',
    avgCPC: 8.60,
    affiliateAvailable: true,
    avgCommission: 40,
    estimatedRPM: 28,
    monthlyRevenuePerSite: 520,
    parasiteSuccessRate: 61,
    avgTimeToRank: 9,
    expiredDomainsAvailable: 623,
    indexationRate: 79,
    competitorCount: 420,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best seo tools', volume: 368000, cpc: 12.40, difficulty: 71 },
      { keyword: 'email marketing software', volume: 201000, cpc: 14.20, difficulty: 68 },
      { keyword: 'social media marketing', volume: 450000, cpc: 5.30, difficulty: 63 },
      { keyword: 'google ads tutorial', volume: 135000, cpc: 8.90, difficulty: 55 },
      { keyword: 'content marketing strategy', volume: 90500, cpc: 7.60, difficulty: 51 },
    ],
    affiliatePrograms: [
      { name: 'SEMrush', commission: '40% recurring', cookie: '120 days', network: 'Impact' },
      { name: 'Ahrefs', commission: '$65-200/sale', cookie: '60 days', network: 'Direct' },
      { name: 'ActiveCampaign', commission: '20-30% recurring', cookie: '90 days', network: 'Direct' },
    ],
  },
  {
    slug: 'saas_software',
    displayName: 'SaaS & Software',
    avgCompetitionScore: 48,
    avgDomainAge: 3.9,
    avgDR: 36,
    topResultsHaveExpired: true,
    totalKeywords: 210000,
    avgMonthlySearches: 14200,
    topKeywordVolume: 673000,
    topKeyword: 'best project management software',
    avgCPC: 12.30,
    affiliateAvailable: true,
    avgCommission: 35,
    estimatedRPM: 32,
    monthlyRevenuePerSite: 680,
    parasiteSuccessRate: 71,
    avgTimeToRank: 6,
    expiredDomainsAvailable: 934,
    indexationRate: 85,
    competitorCount: 290,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best project management software', volume: 673000, cpc: 18.40, difficulty: 72 },
      { keyword: 'crm software comparison', volume: 301000, cpc: 22.10, difficulty: 68 },
      { keyword: 'best accounting software', volume: 246000, cpc: 16.80, difficulty: 65 },
      { keyword: 'video editing software', volume: 823000, cpc: 4.20, difficulty: 58 },
      { keyword: 'best vpn service', volume: 550000, cpc: 8.90, difficulty: 71 },
    ],
    affiliatePrograms: [
      { name: 'Monday.com', commission: '$150-200/sale', cookie: '30 days', network: 'Impact' },
      { name: 'HubSpot', commission: '15% recurring', cookie: '90 days', network: 'Direct' },
      { name: 'Shopify', commission: '$58-2000/sale', cookie: '30 days', network: 'Direct' },
    ],
  },
  {
    slug: 'crypto',
    displayName: 'Crypto & Web3',
    avgCompetitionScore: 63,
    avgDomainAge: 3.2,
    avgDR: 42,
    topResultsHaveExpired: true,
    totalKeywords: 180000,
    avgMonthlySearches: 22000,
    topKeywordVolume: 1800000,
    topKeyword: 'bitcoin price',
    avgCPC: 7.40,
    affiliateAvailable: true,
    avgCommission: 50,
    estimatedRPM: 35,
    monthlyRevenuePerSite: 580,
    parasiteSuccessRate: 48,
    avgTimeToRank: 14,
    expiredDomainsAvailable: 412,
    indexationRate: 71,
    competitorCount: 890,
    difficulty: 'MEDIUM',
    opportunity: 'GOOD',
    topKeywords: [
      { keyword: 'best crypto exchange', volume: 450000, cpc: 12.30, difficulty: 74 },
      { keyword: 'how to buy bitcoin', volume: 368000, cpc: 9.80, difficulty: 69 },
      { keyword: 'crypto wallet comparison', volume: 135000, cpc: 8.40, difficulty: 61 },
      { keyword: 'defi explained', volume: 90500, cpc: 5.20, difficulty: 52 },
      { keyword: 'nft marketplace', volume: 246000, cpc: 3.80, difficulty: 58 },
    ],
    affiliatePrograms: [
      { name: 'Binance', commission: '20-40% trading fees', cookie: '90 days', network: 'Direct' },
      { name: 'Ledger', commission: '10%', cookie: '30 days', network: 'Direct' },
      { name: 'eToro', commission: '$200/deposit', cookie: '30 days', network: 'Impact' },
    ],
  },
  {
    slug: 'ecommerce',
    displayName: 'E-Commerce & Shopping',
    avgCompetitionScore: 67,
    avgDomainAge: 5.6,
    avgDR: 52,
    topResultsHaveExpired: false,
    totalKeywords: 2400000,
    avgMonthlySearches: 45000,
    topKeywordVolume: 2200000,
    topKeyword: 'best laptops',
    avgCPC: 2.10,
    affiliateAvailable: true,
    avgCommission: 4,
    estimatedRPM: 12,
    monthlyRevenuePerSite: 280,
    parasiteSuccessRate: 29,
    avgTimeToRank: 28,
    expiredDomainsAvailable: 189,
    indexationRate: 58,
    competitorCount: 2400,
    difficulty: 'HARD',
    opportunity: 'MODERATE',
    topKeywords: [
      { keyword: 'best laptops 2026', volume: 1200000, cpc: 3.40, difficulty: 82 },
      { keyword: 'amazon deals', volume: 2200000, cpc: 0.80, difficulty: 91 },
      { keyword: 'best headphones', volume: 823000, cpc: 2.90, difficulty: 78 },
      { keyword: 'product reviews', volume: 450000, cpc: 1.20, difficulty: 71 },
      { keyword: 'best gaming chair', volume: 246000, cpc: 2.40, difficulty: 64 },
    ],
    affiliatePrograms: [
      { name: 'Amazon Associates', commission: '1-10%', cookie: '24 hours', network: 'Amazon' },
      { name: 'CJ Affiliate', commission: '2-20%', cookie: '30 days', network: 'CJ' },
      { name: 'ShareASale', commission: '5-30%', cookie: '30 days', network: 'ShareASale' },
    ],
  },
  {
    slug: 'education',
    displayName: 'Online Education',
    avgCompetitionScore: 41,
    avgDomainAge: 4.1,
    avgDR: 34,
    topResultsHaveExpired: true,
    totalKeywords: 340000,
    avgMonthlySearches: 11000,
    topKeywordVolume: 450000,
    topKeyword: 'learn python online',
    avgCPC: 5.60,
    affiliateAvailable: true,
    avgCommission: 45,
    estimatedRPM: 16,
    monthlyRevenuePerSite: 310,
    parasiteSuccessRate: 73,
    avgTimeToRank: 5,
    expiredDomainsAvailable: 1580,
    indexationRate: 88,
    competitorCount: 180,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'learn python free', volume: 450000, cpc: 4.20, difficulty: 52 },
      { keyword: 'best online courses', volume: 368000, cpc: 8.90, difficulty: 61 },
      { keyword: 'coursera vs udemy', volume: 135000, cpc: 6.40, difficulty: 48 },
      { keyword: 'learn web development', volume: 246000, cpc: 5.80, difficulty: 55 },
      { keyword: 'best coding bootcamp', volume: 90500, cpc: 12.30, difficulty: 58 },
    ],
    affiliatePrograms: [
      { name: 'Coursera', commission: '45%', cookie: '30 days', network: 'Linkshare' },
      { name: 'Udemy', commission: '15%', cookie: '7 days', network: 'Direct' },
      { name: 'Skillshare', commission: '$7/trial', cookie: '30 days', network: 'Impact' },
    ],
  },
  {
    slug: 'legal',
    displayName: 'Legal Services',
    avgCompetitionScore: 78,
    avgDomainAge: 8.2,
    avgDR: 62,
    topResultsHaveExpired: false,
    totalKeywords: 89000,
    avgMonthlySearches: 31000,
    topKeywordVolume: 550000,
    topKeyword: 'personal injury lawyer',
    avgCPC: 68.40,
    affiliateAvailable: true,
    avgCommission: 0,
    estimatedRPM: 85,
    monthlyRevenuePerSite: 1240,
    parasiteSuccessRate: 22,
    avgTimeToRank: 35,
    expiredDomainsAvailable: 98,
    indexationRate: 52,
    competitorCount: 1800,
    difficulty: 'VERY HARD',
    opportunity: 'GOOD',
    topKeywords: [
      { keyword: 'personal injury lawyer', volume: 550000, cpc: 92.40, difficulty: 91 },
      { keyword: 'car accident attorney', volume: 368000, cpc: 118.00, difficulty: 89 },
      { keyword: 'divorce lawyer near me', volume: 301000, cpc: 42.30, difficulty: 84 },
      { keyword: 'employment lawyer', volume: 246000, cpc: 38.90, difficulty: 81 },
      { keyword: 'best legal software', volume: 45000, cpc: 18.40, difficulty: 52 },
    ],
    affiliatePrograms: [
      { name: 'LegalZoom', commission: '15-25%', cookie: '30 days', network: 'CJ' },
      { name: 'Rocket Lawyer', commission: '$20/trial', cookie: '45 days', network: 'Direct' },
      { name: 'Martindale-Hubbell', commission: 'Lead gen', cookie: '30 days', network: 'Direct' },
    ],
  },
  {
    slug: 'travel',
    displayName: 'Travel',
    avgCompetitionScore: 71,
    avgDomainAge: 6.4,
    avgDR: 55,
    topResultsHaveExpired: false,
    totalKeywords: 1200000,
    avgMonthlySearches: 38000,
    topKeywordVolume: 2400000,
    topKeyword: 'cheap flights',
    avgCPC: 1.80,
    affiliateAvailable: true,
    avgCommission: 3,
    estimatedRPM: 14,
    monthlyRevenuePerSite: 190,
    parasiteSuccessRate: 24,
    avgTimeToRank: 32,
    expiredDomainsAvailable: 142,
    indexationRate: 55,
    competitorCount: 2100,
    difficulty: 'HARD',
    opportunity: 'MODERATE',
    topKeywords: [
      { keyword: 'cheap flights', volume: 2400000, cpc: 1.20, difficulty: 92 },
      { keyword: 'best travel insurance', volume: 368000, cpc: 8.40, difficulty: 74 },
      { keyword: 'travel credit cards', volume: 246000, cpc: 28.90, difficulty: 79 },
      { keyword: 'best hotels in paris', volume: 135000, cpc: 2.10, difficulty: 68 },
      { keyword: 'digital nomad guide', volume: 90500, cpc: 3.40, difficulty: 48 },
    ],
    affiliatePrograms: [
      { name: 'Booking.com', commission: '25-40%', cookie: '30 days', network: 'Direct' },
      { name: 'Expedia', commission: '2-6%', cookie: '7 days', network: 'CJ' },
      { name: 'World Nomads', commission: '10%', cookie: '60 days', network: 'Direct' },
    ],
  },
  { slug: 'accounting_tax', displayName: 'Accounting & Tax', avgCompetitionScore: 62, avgDomainAge: 6.1, avgDR: 48, topResultsHaveExpired: false, totalKeywords: 45000, avgMonthlySearches: 18000, topKeywordVolume: 450000, topKeyword: 'tax software', avgCPC: 12.40, affiliateAvailable: true, avgCommission: 25, estimatedRPM: 38, monthlyRevenuePerSite: 620, parasiteSuccessRate: 38, avgTimeToRank: 18, expiredDomainsAvailable: 187, indexationRate: 64, competitorCount: 520, difficulty: 'HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'best tax software', volume: 450000, cpc: 18.40, difficulty: 74 }, { keyword: 'small business accounting', volume: 246000, cpc: 14.20, difficulty: 68 }, { keyword: 'tax preparation near me', volume: 368000, cpc: 22.10, difficulty: 71 }, { keyword: 'accounting software comparison', volume: 135000, cpc: 16.80, difficulty: 65 }, { keyword: 'free tax filing', volume: 550000, cpc: 8.90, difficulty: 69 }], affiliatePrograms: [{ name: 'TurboTax', commission: '15-20%', cookie: '30 days', network: 'CJ' }, { name: 'QuickBooks', commission: '$50-150/sale', cookie: '45 days', network: 'CJ' }, { name: 'FreshBooks', commission: '$5-55/sale', cookie: '120 days', network: 'ShareASale' }] },
  { slug: 'addiction_rehab', displayName: 'Addiction & Rehab', avgCompetitionScore: 71, avgDomainAge: 5.8, avgDR: 52, topResultsHaveExpired: false, totalKeywords: 28000, avgMonthlySearches: 22000, topKeywordVolume: 368000, topKeyword: 'drug rehab near me', avgCPC: 42.80, affiliateAvailable: true, avgCommission: 0, estimatedRPM: 72, monthlyRevenuePerSite: 980, parasiteSuccessRate: 28, avgTimeToRank: 28, expiredDomainsAvailable: 98, indexationRate: 58, competitorCount: 890, difficulty: 'HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'drug rehab near me', volume: 368000, cpc: 68.40, difficulty: 84 }, { keyword: 'alcohol treatment centers', volume: 246000, cpc: 52.30, difficulty: 81 }, { keyword: 'addiction treatment programs', volume: 201000, cpc: 44.20, difficulty: 78 }, { keyword: 'substance abuse help', volume: 135000, cpc: 38.90, difficulty: 72 }, { keyword: 'sober living homes', volume: 90500, cpc: 28.40, difficulty: 65 }], affiliatePrograms: [{ name: 'Rehab Lead Gen', commission: '$200-500/lead', cookie: '30 days', network: 'Direct' }, { name: 'Recovery.org', commission: 'Lead gen', cookie: '30 days', network: 'Direct' }] },
  { slug: 'antiques_collectibles', displayName: 'Antiques & Collectibles', avgCompetitionScore: 38, avgDomainAge: 7.2, avgDR: 34, topResultsHaveExpired: true, totalKeywords: 89000, avgMonthlySearches: 8400, topKeywordVolume: 246000, topKeyword: 'antique furniture value', avgCPC: 1.80, affiliateAvailable: true, avgCommission: 8, estimatedRPM: 12, monthlyRevenuePerSite: 180, parasiteSuccessRate: 64, avgTimeToRank: 8, expiredDomainsAvailable: 892, indexationRate: 81, competitorCount: 180, difficulty: 'EASY', opportunity: 'GOOD', topKeywords: [{ keyword: 'antique furniture value', volume: 246000, cpc: 1.20, difficulty: 42 }, { keyword: 'rare coins value', volume: 368000, cpc: 2.40, difficulty: 48 }, { keyword: 'vintage collectibles', volume: 201000, cpc: 1.60, difficulty: 39 }, { keyword: 'antique appraisal online', volume: 135000, cpc: 3.80, difficulty: 45 }, { keyword: 'sports card values', volume: 450000, cpc: 1.90, difficulty: 52 }], affiliatePrograms: [{ name: 'eBay Partner', commission: '1-4%', cookie: '24 hours', network: 'eBay' }, { name: 'Etsy Affiliate', commission: '4%', cookie: '30 days', network: 'Awin' }, { name: 'Heritage Auctions', commission: '5%', cookie: '30 days', network: 'Direct' }] },
  { slug: 'auto_insurance', displayName: 'Auto Insurance', avgCompetitionScore: 88, avgDomainAge: 9.4, avgDR: 71, topResultsHaveExpired: false, totalKeywords: 62000, avgMonthlySearches: 48000, topKeywordVolume: 1800000, topKeyword: 'cheap car insurance', avgCPC: 58.40, affiliateAvailable: true, avgCommission: 0, estimatedRPM: 92, monthlyRevenuePerSite: 1840, parasiteSuccessRate: 14, avgTimeToRank: 45, expiredDomainsAvailable: 42, indexationRate: 38, competitorCount: 3200, difficulty: 'VERY HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'cheap car insurance', volume: 1800000, cpc: 82.40, difficulty: 96 }, { keyword: 'auto insurance quotes', volume: 1200000, cpc: 74.20, difficulty: 94 }, { keyword: 'best car insurance companies', volume: 823000, cpc: 62.10, difficulty: 91 }, { keyword: 'car insurance comparison', volume: 550000, cpc: 58.90, difficulty: 89 }, { keyword: 'full coverage car insurance', volume: 368000, cpc: 48.30, difficulty: 85 }], affiliatePrograms: [{ name: 'The Zebra', commission: '$8-15/lead', cookie: '30 days', network: 'Direct' }, { name: 'Policy Genius', commission: '$50-100/lead', cookie: '30 days', network: 'Direct' }, { name: 'Gabi Insurance', commission: '$20/lead', cookie: '30 days', network: 'Direct' }] },
  { slug: 'baking_desserts', displayName: 'Baking & Desserts', avgCompetitionScore: 35, avgDomainAge: 4.2, avgDR: 28, topResultsHaveExpired: true, totalKeywords: 340000, avgMonthlySearches: 28000, topKeywordVolume: 1200000, topKeyword: 'easy cake recipes', avgCPC: 0.80, affiliateAvailable: true, avgCommission: 5, estimatedRPM: 8, monthlyRevenuePerSite: 140, parasiteSuccessRate: 72, avgTimeToRank: 5, expiredDomainsAvailable: 1840, indexationRate: 89, competitorCount: 140, difficulty: 'EASY', opportunity: 'GOOD', topKeywords: [{ keyword: 'easy cake recipes', volume: 1200000, cpc: 0.60, difficulty: 45 }, { keyword: 'chocolate chip cookies recipe', volume: 823000, cpc: 0.40, difficulty: 42 }, { keyword: 'sourdough bread recipe', volume: 550000, cpc: 0.80, difficulty: 48 }, { keyword: 'best baking tools', volume: 135000, cpc: 2.40, difficulty: 38 }, { keyword: 'dessert recipes easy', volume: 673000, cpc: 0.50, difficulty: 41 }], affiliatePrograms: [{ name: 'Amazon Associates', commission: '3-8%', cookie: '24 hours', network: 'Amazon' }, { name: 'KitchenAid Affiliate', commission: '5%', cookie: '30 days', network: 'CJ' }, { name: 'Williams-Sonoma', commission: '5%', cookie: '14 days', network: 'CJ' }] },
  { slug: 'banking_fintech', displayName: 'Banking & Fintech', avgCompetitionScore: 74, avgDomainAge: 7.6, avgDR: 61, topResultsHaveExpired: false, totalKeywords: 89000, avgMonthlySearches: 34000, topKeywordVolume: 823000, topKeyword: 'best online banks', avgCPC: 22.40, affiliateAvailable: true, avgCommission: 0, estimatedRPM: 48, monthlyRevenuePerSite: 920, parasiteSuccessRate: 26, avgTimeToRank: 32, expiredDomainsAvailable: 124, indexationRate: 54, competitorCount: 1400, difficulty: 'HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'best online banks 2026', volume: 823000, cpc: 28.40, difficulty: 84 }, { keyword: 'fintech apps', volume: 368000, cpc: 12.30, difficulty: 68 }, { keyword: 'best checking accounts', volume: 550000, cpc: 18.90, difficulty: 79 }, { keyword: 'digital banking comparison', volume: 246000, cpc: 16.40, difficulty: 72 }, { keyword: 'neobank review', volume: 135000, cpc: 8.20, difficulty: 58 }], affiliatePrograms: [{ name: 'Chime', commission: '$30/signup', cookie: '30 days', network: 'Impact' }, { name: 'Wise', commission: '$30/referral', cookie: '30 days', network: 'Direct' }, { name: 'Revolut', commission: '$20/signup', cookie: '30 days', network: 'Direct' }] },
  { slug: 'cbd_cannabis', displayName: 'CBD & Cannabis', avgCompetitionScore: 54, avgDomainAge: 3.8, avgDR: 38, topResultsHaveExpired: true, totalKeywords: 68000, avgMonthlySearches: 18000, topKeywordVolume: 450000, topKeyword: 'best cbd oil', avgCPC: 3.20, affiliateAvailable: true, avgCommission: 20, estimatedRPM: 18, monthlyRevenuePerSite: 340, parasiteSuccessRate: 52, avgTimeToRank: 11, expiredDomainsAvailable: 342, indexationRate: 72, competitorCount: 420, difficulty: 'MEDIUM', opportunity: 'GOOD', topKeywords: [{ keyword: 'best cbd oil 2026', volume: 450000, cpc: 4.80, difficulty: 62 }, { keyword: 'cbd oil for anxiety', volume: 368000, cpc: 3.90, difficulty: 58 }, { keyword: 'cbd gummies review', volume: 246000, cpc: 2.80, difficulty: 54 }, { keyword: 'medical marijuana dispensary', volume: 550000, cpc: 2.40, difficulty: 61 }, { keyword: 'cbd vs thc', volume: 201000, cpc: 2.10, difficulty: 48 }], affiliatePrograms: [{ name: 'CBDistillery', commission: '20%', cookie: '30 days', network: 'ShareASale' }, { name: 'Charlotte Web', commission: '10%', cookie: '30 days', network: 'ShareASale' }, { name: 'Joy Organics', commission: '25%', cookie: '60 days', network: 'Direct' }] },
  { slug: 'consumer_electronics', displayName: 'Consumer Electronics', avgCompetitionScore: 72, avgDomainAge: 5.8, avgDR: 58, topResultsHaveExpired: false, totalKeywords: 1800000, avgMonthlySearches: 62000, topKeywordVolume: 2400000, topKeyword: 'best smartphones', avgCPC: 2.80, affiliateAvailable: true, avgCommission: 3, estimatedRPM: 14, monthlyRevenuePerSite: 320, parasiteSuccessRate: 28, avgTimeToRank: 26, expiredDomainsAvailable: 142, indexationRate: 58, competitorCount: 2800, difficulty: 'HARD', opportunity: 'MODERATE', topKeywords: [{ keyword: 'best smartphones 2026', volume: 2400000, cpc: 3.20, difficulty: 88 }, { keyword: 'best laptops under 1000', volume: 1200000, cpc: 4.80, difficulty: 82 }, { keyword: 'best wireless earbuds', volume: 823000, cpc: 3.40, difficulty: 78 }, { keyword: 'best smart tv', volume: 673000, cpc: 2.90, difficulty: 75 }, { keyword: 'best gaming monitor', volume: 450000, cpc: 3.60, difficulty: 71 }], affiliatePrograms: [{ name: 'Amazon Associates', commission: '2.5-4%', cookie: '24 hours', network: 'Amazon' }, { name: 'Best Buy', commission: '1-5%', cookie: '1 day', network: 'Impact' }, { name: 'Newegg', commission: '1-3%', cookie: '7 days', network: 'CJ' }] },
  { slug: 'cybersecurity', displayName: 'Cybersecurity', avgCompetitionScore: 51, avgDomainAge: 4.4, avgDR: 42, topResultsHaveExpired: true, totalKeywords: 124000, avgMonthlySearches: 16000, topKeywordVolume: 550000, topKeyword: 'best antivirus software', avgCPC: 9.80, affiliateAvailable: true, avgCommission: 40, estimatedRPM: 28, monthlyRevenuePerSite: 520, parasiteSuccessRate: 62, avgTimeToRank: 8, expiredDomainsAvailable: 624, indexationRate: 79, competitorCount: 310, difficulty: 'MEDIUM', opportunity: 'HOT', topKeywords: [{ keyword: 'best antivirus 2026', volume: 550000, cpc: 12.40, difficulty: 68 }, { keyword: 'vpn comparison', volume: 450000, cpc: 8.90, difficulty: 64 }, { keyword: 'best password manager', volume: 368000, cpc: 7.80, difficulty: 61 }, { keyword: 'identity theft protection', volume: 246000, cpc: 14.20, difficulty: 72 }, { keyword: 'cybersecurity tools', volume: 135000, cpc: 6.40, difficulty: 52 }], affiliatePrograms: [{ name: 'NordVPN', commission: '40% + recurring', cookie: '30 days', network: 'Direct' }, { name: 'Norton', commission: '$20-100/sale', cookie: '60 days', network: 'CJ' }, { name: '1Password', commission: '25%', cookie: '45 days', network: 'Impact' }] },
  { slug: 'dating_relationships', displayName: 'Dating & Relationships', avgCompetitionScore: 58, avgDomainAge: 5.2, avgDR: 44, topResultsHaveExpired: true, totalKeywords: 210000, avgMonthlySearches: 24000, topKeywordVolume: 1200000, topKeyword: 'best dating apps', avgCPC: 4.20, affiliateAvailable: true, avgCommission: 35, estimatedRPM: 22, monthlyRevenuePerSite: 420, parasiteSuccessRate: 55, avgTimeToRank: 10, expiredDomainsAvailable: 489, indexationRate: 74, competitorCount: 520, difficulty: 'MEDIUM', opportunity: 'HOT', topKeywords: [{ keyword: 'best dating apps 2026', volume: 1200000, cpc: 5.40, difficulty: 72 }, { keyword: 'tinder vs bumble', volume: 450000, cpc: 3.80, difficulty: 61 }, { keyword: 'online dating tips', volume: 368000, cpc: 2.90, difficulty: 54 }, { keyword: 'relationship advice', volume: 673000, cpc: 2.10, difficulty: 48 }, { keyword: 'how to get a girlfriend', volume: 246000, cpc: 1.80, difficulty: 44 }], affiliatePrograms: [{ name: 'Match.com', commission: '$20-40/subscription', cookie: '45 days', network: 'CJ' }, { name: 'eHarmony', commission: '$10-50/lead', cookie: '45 days', network: 'CJ' }, { name: 'Zoosk', commission: '$30/subscription', cookie: '30 days', network: 'CJ' }] },
  { slug: 'dental_oral_care', displayName: 'Dental & Oral Care', avgCompetitionScore: 61, avgDomainAge: 5.4, avgDR: 46, topResultsHaveExpired: true, totalKeywords: 89000, avgMonthlySearches: 22000, topKeywordVolume: 550000, topKeyword: 'dentist near me', avgCPC: 24.80, affiliateAvailable: true, avgCommission: 20, estimatedRPM: 38, monthlyRevenuePerSite: 620, parasiteSuccessRate: 44, avgTimeToRank: 14, expiredDomainsAvailable: 312, indexationRate: 68, competitorCount: 680, difficulty: 'MEDIUM', opportunity: 'GOOD', topKeywords: [{ keyword: 'dentist near me', volume: 550000, cpc: 38.40, difficulty: 78 }, { keyword: 'best electric toothbrush', volume: 368000, cpc: 3.80, difficulty: 58 }, { keyword: 'teeth whitening at home', volume: 450000, cpc: 4.20, difficulty: 54 }, { keyword: 'dental implants cost', volume: 246000, cpc: 42.30, difficulty: 74 }, { keyword: 'invisalign vs braces', volume: 201000, cpc: 18.90, difficulty: 65 }], affiliatePrograms: [{ name: 'Oral-B Affiliate', commission: '5-8%', cookie: '30 days', network: 'CJ' }, { name: 'Smile Direct Club', commission: '$100/lead', cookie: '30 days', network: 'Impact' }, { name: 'Byte', commission: '$150/sale', cookie: '30 days', network: 'Impact' }] },
  { slug: 'developer_tools', displayName: 'Developer Tools', avgCompetitionScore: 44, avgDomainAge: 3.8, avgDR: 36, topResultsHaveExpired: true, totalKeywords: 180000, avgMonthlySearches: 14000, topKeywordVolume: 450000, topKeyword: 'best code editor', avgCPC: 8.40, affiliateAvailable: true, avgCommission: 30, estimatedRPM: 24, monthlyRevenuePerSite: 460, parasiteSuccessRate: 68, avgTimeToRank: 7, expiredDomainsAvailable: 734, indexationRate: 82, competitorCount: 240, difficulty: 'EASY', opportunity: 'HOT', topKeywords: [{ keyword: 'best code editor 2026', volume: 450000, cpc: 6.40, difficulty: 52 }, { keyword: 'github alternatives', volume: 246000, cpc: 8.90, difficulty: 48 }, { keyword: 'best ide for python', volume: 368000, cpc: 4.20, difficulty: 45 }, { keyword: 'docker tutorial', volume: 301000, cpc: 5.80, difficulty: 49 }, { keyword: 'best devops tools', volume: 201000, cpc: 12.40, difficulty: 55 }], affiliatePrograms: [{ name: 'GitHub Copilot', commission: '20%', cookie: '30 days', network: 'Direct' }, { name: 'JetBrains', commission: '25%', cookie: '30 days', network: 'Direct' }, { name: 'DigitalOcean', commission: '$25/signup', cookie: '30 days', network: 'Direct' }] },
  { slug: 'fashion_apparel', displayName: 'Fashion & Apparel', avgCompetitionScore: 68, avgDomainAge: 5.6, avgDR: 52, topResultsHaveExpired: false, totalKeywords: 2800000, avgMonthlySearches: 48000, topKeywordVolume: 2400000, topKeyword: 'women fashion trends', avgCPC: 1.20, affiliateAvailable: true, avgCommission: 8, estimatedRPM: 10, monthlyRevenuePerSite: 180, parasiteSuccessRate: 28, avgTimeToRank: 28, expiredDomainsAvailable: 134, indexationRate: 56, competitorCount: 3400, difficulty: 'HARD', opportunity: 'MODERATE', topKeywords: [{ keyword: 'women fashion trends 2026', volume: 2400000, cpc: 1.40, difficulty: 84 }, { keyword: 'best online clothing stores', volume: 823000, cpc: 2.10, difficulty: 78 }, { keyword: 'affordable fashion', volume: 550000, cpc: 1.60, difficulty: 71 }, { keyword: 'sustainable fashion brands', volume: 368000, cpc: 1.80, difficulty: 64 }, { keyword: 'mens fashion guide', volume: 301000, cpc: 1.20, difficulty: 58 }], affiliatePrograms: [{ name: 'ASOS', commission: '5-7%', cookie: '30 days', network: 'Awin' }, { name: 'Nordstrom', commission: '2-20%', cookie: '7 days', network: 'Rakuten' }, { name: 'FashionNova', commission: '20%', cookie: '30 days', network: 'ShareASale' }] },
  { slug: 'fitness_gyms', displayName: 'Fitness & Gyms', avgCompetitionScore: 52, avgDomainAge: 4.6, avgDR: 40, topResultsHaveExpired: true, totalKeywords: 580000, avgMonthlySearches: 32000, topKeywordVolume: 1800000, topKeyword: 'home workout plan', avgCPC: 2.80, affiliateAvailable: true, avgCommission: 12, estimatedRPM: 16, monthlyRevenuePerSite: 320, parasiteSuccessRate: 58, avgTimeToRank: 9, expiredDomainsAvailable: 682, indexationRate: 76, competitorCount: 580, difficulty: 'MEDIUM', opportunity: 'HOT', topKeywords: [{ keyword: 'home workout plan', volume: 1800000, cpc: 1.80, difficulty: 64 }, { keyword: 'best gym equipment', volume: 450000, cpc: 3.40, difficulty: 58 }, { keyword: 'weight loss workout', volume: 673000, cpc: 2.20, difficulty: 61 }, { keyword: 'gym near me', volume: 2400000, cpc: 4.80, difficulty: 72 }, { keyword: 'best fitness apps', volume: 368000, cpc: 3.60, difficulty: 55 }], affiliatePrograms: [{ name: 'MyProtein', commission: '8%', cookie: '30 days', network: 'Awin' }, { name: 'Bowflex', commission: '3%', cookie: '30 days', network: 'CJ' }, { name: 'Peloton', commission: '$24/lead', cookie: '30 days', network: 'Impact' }] },
  { slug: 'gambling_casinos', displayName: 'Gambling & Casinos', avgCompetitionScore: 81, avgDomainAge: 8.4, avgDR: 64, topResultsHaveExpired: false, totalKeywords: 420000, avgMonthlySearches: 58000, topKeywordVolume: 2400000, topKeyword: 'best online casinos', avgCPC: 12.80, affiliateAvailable: true, avgCommission: 40, estimatedRPM: 58, monthlyRevenuePerSite: 2400, parasiteSuccessRate: 18, avgTimeToRank: 42, expiredDomainsAvailable: 78, indexationRate: 42, competitorCount: 4200, difficulty: 'VERY HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'best online casinos 2026', volume: 2400000, cpc: 18.40, difficulty: 94 }, { keyword: 'online slots real money', volume: 1200000, cpc: 14.20, difficulty: 91 }, { keyword: 'sports betting sites', volume: 823000, cpc: 16.80, difficulty: 88 }, { keyword: 'poker online real money', volume: 550000, cpc: 12.40, difficulty: 85 }, { keyword: 'casino bonuses', volume: 450000, cpc: 8.90, difficulty: 82 }], affiliatePrograms: [{ name: 'Bet365 Affiliate', commission: '20-35% revenue share', cookie: 'Lifetime', network: 'Direct' }, { name: '888 Casino', commission: '30-40% revenue share', cookie: 'Lifetime', network: 'Direct' }, { name: 'DraftKings', commission: '25% revenue share', cookie: '30 days', network: 'Direct' }] },
  { slug: 'home_improvement', displayName: 'Home Improvement & DIY', avgCompetitionScore: 48, avgDomainAge: 5.2, avgDR: 42, topResultsHaveExpired: true, totalKeywords: 890000, avgMonthlySearches: 34000, topKeywordVolume: 1200000, topKeyword: 'home renovation ideas', avgCPC: 3.40, affiliateAvailable: true, avgCommission: 6, estimatedRPM: 16, monthlyRevenuePerSite: 280, parasiteSuccessRate: 61, avgTimeToRank: 9, expiredDomainsAvailable: 842, indexationRate: 78, competitorCount: 480, difficulty: 'MEDIUM', opportunity: 'HOT', topKeywords: [{ keyword: 'home renovation ideas', volume: 1200000, cpc: 2.40, difficulty: 62 }, { keyword: 'bathroom remodel cost', volume: 550000, cpc: 4.80, difficulty: 58 }, { keyword: 'best power tools', volume: 368000, cpc: 3.60, difficulty: 54 }, { keyword: 'kitchen renovation tips', volume: 450000, cpc: 3.20, difficulty: 56 }, { keyword: 'diy home projects', volume: 673000, cpc: 1.80, difficulty: 48 }], affiliatePrograms: [{ name: 'Home Depot', commission: '1-8%', cookie: '1 day', network: 'Impact' }, { name: 'Wayfair', commission: '7%', cookie: '7 days', network: 'CJ' }, { name: 'BuildDirect', commission: '5%', cookie: '30 days', network: 'ShareASale' }] },
  { slug: 'hotels_resorts', displayName: 'Hotels & Resorts', avgCompetitionScore: 72, avgDomainAge: 6.8, avgDR: 58, topResultsHaveExpired: false, totalKeywords: 1400000, avgMonthlySearches: 52000, topKeywordVolume: 2400000, topKeyword: 'best hotels', avgCPC: 2.80, affiliateAvailable: true, avgCommission: 4, estimatedRPM: 18, monthlyRevenuePerSite: 340, parasiteSuccessRate: 24, avgTimeToRank: 31, expiredDomainsAvailable: 168, indexationRate: 54, competitorCount: 2800, difficulty: 'HARD', opportunity: 'MODERATE', topKeywords: [{ keyword: 'best hotels in dubai', volume: 823000, cpc: 3.40, difficulty: 78 }, { keyword: 'cheap hotels near me', volume: 2400000, cpc: 2.20, difficulty: 84 }, { keyword: 'luxury resorts', volume: 550000, cpc: 4.80, difficulty: 74 }, { keyword: 'all inclusive resorts', volume: 673000, cpc: 3.60, difficulty: 76 }, { keyword: 'hotel booking deals', volume: 450000, cpc: 2.40, difficulty: 72 }], affiliatePrograms: [{ name: 'Booking.com', commission: '25-40%', cookie: '30 days', network: 'Direct' }, { name: 'Hotels.com', commission: '4%', cookie: '7 days', network: 'CJ' }, { name: 'Marriott', commission: '3-6%', cookie: '7 days', network: 'Rakuten' }] },
  { slug: 'make_money_online', displayName: 'Make Money Online', avgCompetitionScore: 62, avgDomainAge: 4.8, avgDR: 46, topResultsHaveExpired: true, totalKeywords: 280000, avgMonthlySearches: 28000, topKeywordVolume: 1200000, topKeyword: 'how to make money online', avgCPC: 3.80, affiliateAvailable: true, avgCommission: 50, estimatedRPM: 24, monthlyRevenuePerSite: 480, parasiteSuccessRate: 44, avgTimeToRank: 13, expiredDomainsAvailable: 384, indexationRate: 69, competitorCount: 840, difficulty: 'MEDIUM', opportunity: 'GOOD', topKeywords: [{ keyword: 'how to make money online', volume: 1200000, cpc: 4.20, difficulty: 74 }, { keyword: 'passive income ideas', volume: 673000, cpc: 3.80, difficulty: 68 }, { keyword: 'best side hustles', volume: 550000, cpc: 3.40, difficulty: 64 }, { keyword: 'freelance jobs online', volume: 450000, cpc: 2.80, difficulty: 58 }, { keyword: 'dropshipping guide', volume: 368000, cpc: 4.60, difficulty: 62 }], affiliatePrograms: [{ name: 'ClickBank', commission: '50-75%', cookie: '60 days', network: 'ClickBank' }, { name: 'Shopify', commission: '$58-2000/sale', cookie: '30 days', network: 'Direct' }, { name: 'Wealthy Affiliate', commission: '$23/month recurring', cookie: 'Lifetime', network: 'Direct' }] },
  { slug: 'mental_health', displayName: 'Mental Health & Therapy', avgCompetitionScore: 54, avgDomainAge: 4.8, avgDR: 42, topResultsHaveExpired: true, totalKeywords: 320000, avgMonthlySearches: 28000, topKeywordVolume: 823000, topKeyword: 'online therapy', avgCPC: 8.40, affiliateAvailable: true, avgCommission: 25, estimatedRPM: 28, monthlyRevenuePerSite: 520, parasiteSuccessRate: 56, avgTimeToRank: 10, expiredDomainsAvailable: 542, indexationRate: 75, competitorCount: 420, difficulty: 'MEDIUM', opportunity: 'HOT', topKeywords: [{ keyword: 'online therapy', volume: 823000, cpc: 12.40, difficulty: 68 }, { keyword: 'best therapy apps', volume: 450000, cpc: 8.90, difficulty: 61 }, { keyword: 'anxiety treatment', volume: 673000, cpc: 6.40, difficulty: 64 }, { keyword: 'depression help', volume: 550000, cpc: 5.80, difficulty: 62 }, { keyword: 'betterhelp vs talkspace', volume: 246000, cpc: 14.20, difficulty: 58 }], affiliatePrograms: [{ name: 'BetterHelp', commission: '$60-90/signup', cookie: '30 days', network: 'Impact' }, { name: 'Talkspace', commission: '$65/signup', cookie: '30 days', network: 'Direct' }, { name: 'Calm', commission: '$20/subscription', cookie: '30 days', network: 'Impact' }] },
  { slug: 'music_instruments', displayName: 'Music & Instruments', avgCompetitionScore: 38, avgDomainAge: 5.6, avgDR: 34, topResultsHaveExpired: true, totalKeywords: 420000, avgMonthlySearches: 22000, topKeywordVolume: 823000, topKeyword: 'learn guitar online', avgCPC: 1.80, affiliateAvailable: true, avgCommission: 8, estimatedRPM: 12, monthlyRevenuePerSite: 220, parasiteSuccessRate: 66, avgTimeToRank: 7, expiredDomainsAvailable: 1240, indexationRate: 82, competitorCount: 220, difficulty: 'EASY', opportunity: 'GOOD', topKeywords: [{ keyword: 'learn guitar online free', volume: 823000, cpc: 1.20, difficulty: 48 }, { keyword: 'best acoustic guitars', volume: 450000, cpc: 2.80, difficulty: 54 }, { keyword: 'music production software', volume: 368000, cpc: 4.20, difficulty: 58 }, { keyword: 'piano lessons online', volume: 301000, cpc: 3.40, difficulty: 52 }, { keyword: 'best digital piano', volume: 246000, cpc: 3.60, difficulty: 55 }], affiliatePrograms: [{ name: 'Guitar Center', commission: '6%', cookie: '14 days', network: 'CJ' }, { name: 'Fender Play', commission: '$10/signup', cookie: '30 days', network: 'Direct' }, { name: 'Sweetwater', commission: '4%', cookie: '30 days', network: 'ShareASale' }] },
  { slug: 'pets_dogs', displayName: 'Pets — Dogs', avgCompetitionScore: 42, avgDomainAge: 4.8, avgDR: 36, topResultsHaveExpired: true, totalKeywords: 580000, avgMonthlySearches: 38000, topKeywordVolume: 1800000, topKeyword: 'best dog food', avgCPC: 2.40, affiliateAvailable: true, avgCommission: 8, estimatedRPM: 14, monthlyRevenuePerSite: 260, parasiteSuccessRate: 68, avgTimeToRank: 6, expiredDomainsAvailable: 1480, indexationRate: 84, competitorCount: 280, difficulty: 'EASY', opportunity: 'HOT', topKeywords: [{ keyword: 'best dog food 2026', volume: 1800000, cpc: 2.80, difficulty: 58 }, { keyword: 'dog training tips', volume: 823000, cpc: 1.60, difficulty: 48 }, { keyword: 'puppy care guide', volume: 550000, cpc: 1.40, difficulty: 44 }, { keyword: 'best dog breeds', volume: 673000, cpc: 1.20, difficulty: 46 }, { keyword: 'dog insurance comparison', volume: 246000, cpc: 8.40, difficulty: 62 }], affiliatePrograms: [{ name: 'Chewy', commission: '4-8%', cookie: '15 days', network: 'Impact' }, { name: 'Petco', commission: '4%', cookie: '7 days', network: 'CJ' }, { name: 'Bark Box', commission: '$18/signup', cookie: '30 days', network: 'Impact' }] },
  { slug: 'pets_cats', displayName: 'Pets — Cats', avgCompetitionScore: 38, avgDomainAge: 4.4, avgDR: 32, topResultsHaveExpired: true, totalKeywords: 380000, avgMonthlySearches: 28000, topKeywordVolume: 1200000, topKeyword: 'best cat food', avgCPC: 1.80, affiliateAvailable: true, avgCommission: 8, estimatedRPM: 12, monthlyRevenuePerSite: 210, parasiteSuccessRate: 71, avgTimeToRank: 5, expiredDomainsAvailable: 1620, indexationRate: 86, competitorCount: 220, difficulty: 'EASY', opportunity: 'HOT', topKeywords: [{ keyword: 'best cat food 2026', volume: 1200000, cpc: 2.20, difficulty: 52 }, { keyword: 'cat care tips', volume: 550000, cpc: 1.20, difficulty: 42 }, { keyword: 'indoor cat breeds', volume: 368000, cpc: 1.00, difficulty: 38 }, { keyword: 'best cat litter box', volume: 301000, cpc: 2.80, difficulty: 48 }, { keyword: 'cat health problems', volume: 246000, cpc: 2.40, difficulty: 52 }], affiliatePrograms: [{ name: 'Chewy', commission: '4-8%', cookie: '15 days', network: 'Impact' }, { name: 'PrettyLitter', commission: '15%', cookie: '30 days', network: 'ShareASale' }, { name: 'Petco', commission: '4%', cookie: '7 days', network: 'CJ' }] },
  { slug: 'real_estate', displayName: 'Real Estate', avgCompetitionScore: 76, avgDomainAge: 7.2, avgDR: 62, topResultsHaveExpired: false, totalKeywords: 680000, avgMonthlySearches: 48000, topKeywordVolume: 2400000, topKeyword: 'homes for sale near me', avgCPC: 4.80, affiliateAvailable: true, avgCommission: 0, estimatedRPM: 32, monthlyRevenuePerSite: 580, parasiteSuccessRate: 22, avgTimeToRank: 38, expiredDomainsAvailable: 98, indexationRate: 48, competitorCount: 2400, difficulty: 'VERY HARD', opportunity: 'GOOD', topKeywords: [{ keyword: 'homes for sale near me', volume: 2400000, cpc: 6.40, difficulty: 88 }, { keyword: 'real estate investing', volume: 823000, cpc: 5.80, difficulty: 81 }, { keyword: 'best real estate markets', volume: 450000, cpc: 4.20, difficulty: 74 }, { keyword: 'how to buy a house', volume: 673000, cpc: 3.80, difficulty: 76 }, { keyword: 'real estate agent near me', volume: 550000, cpc: 8.90, difficulty: 82 }], affiliatePrograms: [{ name: 'Zillow Flex', commission: 'Lead gen', cookie: '30 days', network: 'Direct' }, { name: 'Roofstock', commission: '$200/deal', cookie: '30 days', network: 'Direct' }, { name: 'Fundrise', commission: '$50/signup', cookie: '30 days', network: 'Impact' }] },
  { slug: 'recipes_cooking', displayName: 'Recipes & Cooking', avgCompetitionScore: 52, avgDomainAge: 4.8, avgDR: 38, topResultsHaveExpired: true, totalKeywords: 4800000, avgMonthlySearches: 62000, topKeywordVolume: 8100000, topKeyword: 'easy dinner recipes', avgCPC: 0.60, affiliateAvailable: true, avgCommission: 5, estimatedRPM: 8, monthlyRevenuePerSite: 160, parasiteSuccessRate: 54, avgTimeToRank: 10, expiredDomainsAvailable: 1840, indexationRate: 78, competitorCount: 1200, difficulty: 'MEDIUM', opportunity: 'GOOD', topKeywords: [{ keyword: 'easy dinner recipes', volume: 8100000, cpc: 0.40, difficulty: 68 }, { keyword: 'healthy meal prep', volume: 2400000, cpc: 0.80, difficulty: 62 }, { keyword: 'air fryer recipes', volume: 1800000, cpc: 0.60, difficulty: 58 }, { keyword: 'instant pot recipes', volume: 1200000, cpc: 0.50, difficulty: 55 }, { keyword: 'keto recipes easy', volume: 823000, cpc: 1.20, difficulty: 52 }], affiliatePrograms: [{ name: 'Amazon Associates', commission: '3-8%', cookie: '24 hours', network: 'Amazon' }, { name: 'HelloFresh', commission: '$10-15/signup', cookie: '30 days', network: 'Impact' }, { name: 'Thrive Market', commission: '5%', cookie: '14 days', network: 'CJ' }] },
  {
    slug: 'skincare_cosmetics',
    displayName: 'Skincare & Cosmetics',
    avgCompetitionScore: 58,
    avgDomainAge: 4.4,
    avgDR: 44,
    topResultsHaveExpired: true,
    totalKeywords: 680000,
    avgMonthlySearches: 42000,
    topKeywordVolume: 1800000,
    topKeyword: 'best skincare routine',
    avgCPC: 2.20,
    affiliateAvailable: true,
    avgCommission: 12,
    estimatedRPM: 16,
    monthlyRevenuePerSite: 320,
    parasiteSuccessRate: 52,
    avgTimeToRank: 11,
    expiredDomainsAvailable: 684,
    indexationRate: 74,
    competitorCount: 680,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best skincare routine', volume: 1800000, cpc: 2.40, difficulty: 68 },
      { keyword: 'best moisturizer for dry skin', volume: 823000, cpc: 3.20, difficulty: 62 },
      { keyword: 'anti aging skincare', volume: 673000, cpc: 4.80, difficulty: 65 },
      { keyword: 'best foundation for oily skin', volume: 550000, cpc: 2.80, difficulty: 58 },
      { keyword: 'sunscreen comparison', volume: 368000, cpc: 2.10, difficulty: 52 }
    ],
    affiliatePrograms: [
      { name: 'Sephora', commission: '5-10%', cookie: '14 days', network: 'Rakuten' },
      { name: 'The Ordinary', commission: '8%', cookie: '30 days', network: 'Awin' },
      { name: 'Paula Choice', commission: '10%', cookie: '30 days', network: 'ShareASale' }
    ]
  },
  {
    slug: 'solar_energy',
    displayName: 'Solar Energy',
    avgCompetitionScore: 58,
    avgDomainAge: 4.2,
    avgDR: 42,
    topResultsHaveExpired: true,
    totalKeywords: 68000,
    avgMonthlySearches: 24000,
    topKeywordVolume: 550000,
    topKeyword: 'solar panels cost',
    avgCPC: 14.80,
    affiliateAvailable: true,
    avgCommission: 0,
    estimatedRPM: 42,
    monthlyRevenuePerSite: 780,
    parasiteSuccessRate: 52,
    avgTimeToRank: 11,
    expiredDomainsAvailable: 342,
    indexationRate: 72,
    competitorCount: 380,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'solar panels cost 2026', volume: 550000, cpc: 18.40, difficulty: 68 },
      { keyword: 'best solar companies', volume: 368000, cpc: 22.10, difficulty: 72 },
      { keyword: 'solar panel installation', volume: 450000, cpc: 16.80, difficulty: 65 },
      { keyword: 'home solar system', volume: 301000, cpc: 12.40, difficulty: 61 },
      { keyword: 'solar energy savings', volume: 246000, cpc: 8.90, difficulty: 54 }
    ],
    affiliatePrograms: [
      { name: 'SunPower', commission: '$400-800/lead', cookie: '30 days', network: 'Direct' },
      { name: 'Palmetto Solar', commission: '$300/lead', cookie: '30 days', network: 'Direct' },
      { name: 'EnergySage', commission: '$200/lead', cookie: '30 days', network: 'Direct' }
    ]
  },
  {
    slug: 'video_games',
    displayName: 'Video Games',
    avgCompetitionScore: 55,
    avgDomainAge: 4.8,
    avgDR: 44,
    topResultsHaveExpired: true,
    totalKeywords: 1200000,
    avgMonthlySearches: 48000,
    topKeywordVolume: 2400000,
    topKeyword: 'best games 2026',
    avgCPC: 1.40,
    affiliateAvailable: true,
    avgCommission: 5,
    estimatedRPM: 12,
    monthlyRevenuePerSite: 240,
    parasiteSuccessRate: 58,
    avgTimeToRank: 9,
    expiredDomainsAvailable: 824,
    indexationRate: 78,
    competitorCount: 680,
    difficulty: 'MEDIUM',
    opportunity: 'GOOD',
    topKeywords: [
      { keyword: 'best games 2026', volume: 2400000, cpc: 1.60, difficulty: 72 },
      { keyword: 'best gaming pc build', volume: 823000, cpc: 3.40, difficulty: 64 },
      { keyword: 'game pass vs ps plus', volume: 550000, cpc: 2.80, difficulty: 58 },
      { keyword: 'best gaming headset', volume: 673000, cpc: 2.40, difficulty: 61 },
      { keyword: 'roblox codes', volume: 1800000, cpc: 0.80, difficulty: 52 }
    ],
    affiliatePrograms: [
      { name: 'Fanatical', commission: '5%', cookie: '30 days', network: 'Awin' },
      { name: 'Humble Bundle', commission: '5%', cookie: '30 days', network: 'Impact' },
      { name: 'Xbox Affiliate', commission: '2%', cookie: '14 days', network: 'Rakuten' }
    ]
  },
  {
    slug: 'web_hosting',
    displayName: 'Web Hosting & Cloud',
    avgCompetitionScore: 62,
    avgDomainAge: 5.8,
    avgDR: 52,
    topResultsHaveExpired: true,
    totalKeywords: 89000,
    avgMonthlySearches: 18000,
    topKeywordVolume: 823000,
    topKeyword: 'best web hosting',
    avgCPC: 7.80,
    affiliateAvailable: true,
    avgCommission: 65,
    estimatedRPM: 32,
    monthlyRevenuePerSite: 680,
    parasiteSuccessRate: 48,
    avgTimeToRank: 12,
    expiredDomainsAvailable: 428,
    indexationRate: 72,
    competitorCount: 580,
    difficulty: 'MEDIUM',
    opportunity: 'GOOD',
    topKeywords: [
      { keyword: 'best web hosting 2026', volume: 823000, cpc: 12.40, difficulty: 74 },
      { keyword: 'cheap web hosting', volume: 550000, cpc: 8.90, difficulty: 68 },
      { keyword: 'wordpress hosting comparison', volume: 368000, cpc: 9.80, difficulty: 65 },
      { keyword: 'vps hosting review', volume: 246000, cpc: 7.40, difficulty: 61 },
      { keyword: 'cloud hosting providers', volume: 201000, cpc: 14.20, difficulty: 64 }
    ],
    affiliatePrograms: [
      { name: 'Bluehost', commission: '$65-130/sale', cookie: '90 days', network: 'CJ' },
      { name: 'SiteGround', commission: '$50-100/sale', cookie: '60 days', network: 'Direct' },
      { name: 'Hostinger', commission: '60%', cookie: '30 days', network: 'Impact' }
    ]
  },
  {
    slug: 'womens_health',
    displayName: "Women's Health",
    avgCompetitionScore: 48,
    avgDomainAge: 4.6,
    avgDR: 38,
    topResultsHaveExpired: true,
    totalKeywords: 420000,
    avgMonthlySearches: 32000,
    topKeywordVolume: 1200000,
    topKeyword: 'womens health tips',
    avgCPC: 3.20,
    affiliateAvailable: true,
    avgCommission: 18,
    estimatedRPM: 20,
    monthlyRevenuePerSite: 380,
    parasiteSuccessRate: 64,
    avgTimeToRank: 8,
    expiredDomainsAvailable: 892,
    indexationRate: 80,
    competitorCount: 380,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'womens health tips', volume: 1200000, cpc: 2.40, difficulty: 58 },
      { keyword: 'pcos symptoms treatment', volume: 450000, cpc: 4.80, difficulty: 54 },
      { keyword: 'pregnancy nutrition guide', volume: 368000, cpc: 3.20, difficulty: 52 },
      { keyword: 'menopause symptoms relief', volume: 301000, cpc: 5.60, difficulty: 56 },
      { keyword: 'best prenatal vitamins', volume: 246000, cpc: 4.20, difficulty: 49 }
    ],
    affiliatePrograms: [
      { name: 'Flo Health', commission: '20%', cookie: '30 days', network: 'Impact' },
      { name: 'Ritual Vitamins', commission: '10%', cookie: '30 days', network: 'ShareASale' },
      { name: 'Hims & Hers', commission: '$20/signup', cookie: '30 days', network: 'Impact' }
    ]
  },
  {
    slug: 'yoga_mindfulness',
    displayName: 'Yoga & Mindfulness',
    avgCompetitionScore: 36,
    avgDomainAge: 4.2,
    avgDR: 30,
    topResultsHaveExpired: true,
    totalKeywords: 280000,
    avgMonthlySearches: 22000,
    topKeywordVolume: 823000,
    topKeyword: 'yoga for beginners',
    avgCPC: 1.80,
    affiliateAvailable: true,
    avgCommission: 20,
    estimatedRPM: 14,
    monthlyRevenuePerSite: 260,
    parasiteSuccessRate: 74,
    avgTimeToRank: 4,
    expiredDomainsAvailable: 1840,
    indexationRate: 88,
    competitorCount: 180,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'yoga for beginners', volume: 823000, cpc: 1.40, difficulty: 48 },
      { keyword: 'meditation apps review', volume: 450000, cpc: 3.80, difficulty: 52 },
      { keyword: 'best yoga mat', volume: 368000, cpc: 2.40, difficulty: 45 },
      { keyword: 'mindfulness exercises', volume: 301000, cpc: 2.20, difficulty: 42 },
      { keyword: 'online yoga classes', volume: 246000, cpc: 4.20, difficulty: 49 }
    ],
    affiliatePrograms: [
      { name: 'Manduka', commission: '10%', cookie: '30 days', network: 'ShareASale' },
      { name: 'Alo Moves', commission: '20%', cookie: '30 days', network: 'Impact' },
      { name: 'Headspace', commission: '$10/signup', cookie: '30 days', network: 'Impact' }
    ]
  },
  {
    slug: 'supplements_vitamins',
    displayName: 'Supplements & Vitamins',
    avgCompetitionScore: 52,
    avgDomainAge: 4.8,
    avgDR: 40,
    topResultsHaveExpired: true,
    totalKeywords: 380000,
    avgMonthlySearches: 34000,
    topKeywordVolume: 1200000,
    topKeyword: 'best multivitamins',
    avgCPC: 4.20,
    affiliateAvailable: true,
    avgCommission: 20,
    estimatedRPM: 22,
    monthlyRevenuePerSite: 420,
    parasiteSuccessRate: 61,
    avgTimeToRank: 9,
    expiredDomainsAvailable: 724,
    indexationRate: 78,
    competitorCount: 480,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best multivitamins 2026', volume: 1200000, cpc: 5.40, difficulty: 64 },
      { keyword: 'best protein powder', volume: 823000, cpc: 4.80, difficulty: 62 },
      { keyword: 'creatine benefits', volume: 550000, cpc: 3.20, difficulty: 54 },
      { keyword: 'best collagen supplements', volume: 450000, cpc: 4.60, difficulty: 58 },
      { keyword: 'vitamin d deficiency', volume: 673000, cpc: 2.80, difficulty: 52 }
    ],
    affiliatePrograms: [
      { name: 'iHerb', commission: '5-10%', cookie: '7 days', network: 'Direct' },
      { name: 'Transparent Labs', commission: '10%', cookie: '30 days', network: 'ShareASale' },
      { name: 'Legion Athletics', commission: '10%', cookie: '60 days', network: 'ShareASale' }
    ]
  },
  // ============================================
  // STREAMING SERVICES — HIGH OPPORTUNITY
  // ============================================
  {
    slug: 'streaming_services',
    displayName: 'Streaming Services',
    avgCompetitionScore: 58,
    avgDomainAge: 3.8,
    avgDR: 44,
    topResultsHaveExpired: true,
    totalKeywords: 280000,
    avgMonthlySearches: 48000,
    topKeywordVolume: 2400000,
    topKeyword: 'best streaming services',
    avgCPC: 3.40,
    affiliateAvailable: true,
    avgCommission: 25,
    estimatedRPM: 22,
    monthlyRevenuePerSite: 480,
    parasiteSuccessRate: 58,
    avgTimeToRank: 9,
    expiredDomainsAvailable: 524,
    indexationRate: 76,
    competitorCount: 420,
    difficulty: 'MEDIUM',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best streaming services 2026', volume: 2400000, cpc: 4.20, difficulty: 72 },
      { keyword: 'netflix vs disney plus', volume: 823000, cpc: 3.80, difficulty: 64 },
      { keyword: 'cheapest streaming bundles', volume: 550000, cpc: 3.20, difficulty: 58 },
      { keyword: 'hbo max vs netflix', volume: 450000, cpc: 3.60, difficulty: 61 },
      { keyword: 'best streaming for movies', volume: 368000, cpc: 2.80, difficulty: 55 },
      { keyword: 'streaming service comparison', volume: 301000, cpc: 4.40, difficulty: 59 },
      { keyword: 'cord cutting guide', volume: 246000, cpc: 2.60, difficulty: 52 },
      { keyword: 'free streaming services', volume: 673000, cpc: 1.80, difficulty: 56 }
    ],
    affiliatePrograms: [
      { name: 'Netflix (via button)', commission: '$20-40/signup', cookie: '30 days', network: 'Impact' },
      { name: 'Disney+', commission: '$10-25/signup', cookie: '30 days', network: 'CJ' },
      { name: 'Hulu', commission: '$4-20/signup', cookie: '30 days', network: 'CJ' },
      { name: 'Sling TV', commission: '$30/signup', cookie: '30 days', network: 'Impact' },
      { name: 'fuboTV', commission: '$30/signup', cookie: '30 days', network: 'Impact' }
    ]
  },
  // ============================================
  // IPTV — HIGHEST OPPORTUNITY RIGHT NOW
  // ============================================
  {
    slug: 'iptv',
    displayName: 'IPTV Services',
    avgCompetitionScore: 28,
    avgDomainAge: 2.8,
    avgDR: 22,
    topResultsHaveExpired: true,
    totalKeywords: 180000,
    avgMonthlySearches: 38000,
    topKeywordVolume: 1800000,
    topKeyword: 'best iptv service',
    avgCPC: 1.20,
    affiliateAvailable: true,
    avgCommission: 40,
    estimatedRPM: 18,
    monthlyRevenuePerSite: 620,
    parasiteSuccessRate: 82,
    avgTimeToRank: 4,
    expiredDomainsAvailable: 2840,
    indexationRate: 91,
    competitorCount: 89,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best iptv service 2026', volume: 1800000, cpc: 1.40, difficulty: 32 },
      { keyword: 'iptv subscription', volume: 1200000, cpc: 1.20, difficulty: 28 },
      { keyword: 'iptv providers review', volume: 823000, cpc: 1.60, difficulty: 34 },
      { keyword: 'best iptv for firestick', volume: 673000, cpc: 1.10, difficulty: 30 },
      { keyword: 'iptv vs cable', volume: 450000, cpc: 0.90, difficulty: 26 },
      { keyword: 'iptv free trial', volume: 550000, cpc: 1.30, difficulty: 29 },
      { keyword: 'iptv smarters setup', volume: 368000, cpc: 0.80, difficulty: 24 },
      { keyword: 'best iptv app', volume: 823000, cpc: 1.00, difficulty: 31 },
      { keyword: 'iptv m3u playlist', volume: 450000, cpc: 0.60, difficulty: 22 },
      { keyword: 'iptv reddit recommendations', volume: 246000, cpc: 0.70, difficulty: 25 }
    ],
    affiliatePrograms: [
      { name: 'IPTV Direct Providers', commission: '30-50% recurring', cookie: '60 days', network: 'Direct' },
      { name: 'StreamLocator VPN', commission: '35%', cookie: '45 days', network: 'Direct' },
      { name: 'NordVPN (for IPTV)', commission: '40%', cookie: '30 days', network: 'Direct' },
      { name: 'ExpressVPN', commission: '$13-36/sale', cookie: '30 days', network: 'Impact' }
    ]
  },
  // ============================================
  // IPTV RELATED NICHES
  // ============================================
  {
    slug: 'iptv_players',
    displayName: 'IPTV Players & Apps',
    avgCompetitionScore: 22,
    avgDomainAge: 2.4,
    avgDR: 18,
    topResultsHaveExpired: true,
    totalKeywords: 89000,
    avgMonthlySearches: 22000,
    topKeywordVolume: 823000,
    topKeyword: 'best iptv player',
    avgCPC: 0.80,
    affiliateAvailable: true,
    avgCommission: 35,
    estimatedRPM: 14,
    monthlyRevenuePerSite: 340,
    parasiteSuccessRate: 86,
    avgTimeToRank: 3,
    expiredDomainsAvailable: 3420,
    indexationRate: 93,
    competitorCount: 42,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best iptv player android', volume: 823000, cpc: 0.90, difficulty: 26 },
      { keyword: 'tivimate review', volume: 450000, cpc: 0.70, difficulty: 22 },
      { keyword: 'iptv smarters pro review', volume: 368000, cpc: 0.80, difficulty: 24 },
      { keyword: 'kodi iptv setup', volume: 550000, cpc: 0.60, difficulty: 28 },
      { keyword: 'best iptv player firestick', volume: 673000, cpc: 0.85, difficulty: 25 }
    ],
    affiliatePrograms: [
      { name: 'TiviMate Premium', commission: '30%', cookie: '30 days', network: 'Direct' },
      { name: 'VPN Providers', commission: '35-40%', cookie: '30 days', network: 'Various' }
    ]
  },
  {
    slug: 'streaming_devices',
    displayName: 'Streaming Devices',
    avgCompetitionScore: 48,
    avgDomainAge: 3.8,
    avgDR: 36,
    topResultsHaveExpired: true,
    totalKeywords: 124000,
    avgMonthlySearches: 28000,
    topKeywordVolume: 1200000,
    topKeyword: 'best streaming device',
    avgCPC: 2.40,
    affiliateAvailable: true,
    avgCommission: 4,
    estimatedRPM: 16,
    monthlyRevenuePerSite: 280,
    parasiteSuccessRate: 66,
    avgTimeToRank: 7,
    expiredDomainsAvailable: 724,
    indexationRate: 82,
    competitorCount: 280,
    difficulty: 'EASY',
    opportunity: 'HOT',
    topKeywords: [
      { keyword: 'best streaming device 2026', volume: 1200000, cpc: 2.80, difficulty: 58 },
      { keyword: 'firestick vs roku', volume: 823000, cpc: 2.20, difficulty: 52 },
      { keyword: 'best 4k streaming device', volume: 550000, cpc: 3.40, difficulty: 56 },
      { keyword: 'apple tv review', volume: 450000, cpc: 2.60, difficulty: 61 },
      { keyword: 'nvidia shield review', volume: 246000, cpc: 2.10, difficulty: 48 }
    ],
    affiliatePrograms: [
      { name: 'Amazon FireTV', commission: '3-4%', cookie: '24 hours', network: 'Amazon' },
      { name: 'Roku Affiliate', commission: '2-4%', cookie: '30 days', network: 'CJ' },
      { name: 'Best Buy', commission: '1-5%', cookie: '1 day', network: 'Impact' }
    ]
  }
]

async function seed() {
  console.log('🌱 Seeding NicheIntelligence data...')
  let count = 0
  for (const niche of NICHE_INTELLIGENCE_DATA) {
    await prisma.nicheIntelligence.upsert({
      where: { slug: niche.slug },
      update: { ...niche, lastAnalyzed: new Date(), dataSource: 'seeded' },
      create: { ...niche, lastAnalyzed: new Date(), dataSource: 'seeded' },
    })
    count++
    console.log(`  ✅ ${niche.displayName}`)
  }
  console.log(`\n✨ Seeded ${count} niches successfully.`)
}

seed()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
